name: Publish to GHCR

on:
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/ThijmenGThN/papermc

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/thijmengthn/papermc:latest
